"""
Central import file for PySide6 components.

This module serves as a single point of import for commonly used PySide6 classes,
organized by their respective modules (QtCore, QtGui, QtWidgets, QtCharts).
It simplifies imports across the project and provides better dependency management.

Usage:
    from core.common import QMainWindow, QPushButton, QVBoxLayout
"""

from PySide6.QtCharts import (
    QChart,
    QChartView,
    QBarSet,
    QBarSeries,
    QValueAxis,
    QBarCategoryAxis,
    QPieSeries,
    QPieSlice,
)
from PySide6.QtCore import (
    Qt,
    QDate,
    QSize,
    Signal,
    QEvent,
    QObject,
    QTimer,
    QStringListModel,
    QPoint,
    QAbstractTableModel,
    QModelIndex,
    QSortFilterProxyModel,
    QPropertyAnimation,
    QEasingCurve,
)

from PySide6.QtGui import (
    QPainter,
    QIcon,
    QPixmap,
    QImage,
    QAction,
    QColor,
    QCloseEvent,
    QFontDatabase,
    QDoubleValidator,
    QFont,
    QMouseEvent,
    QPalette,
)

from PySide6.QtWidgets import (
    QApplication,
    QComboBox,
    QCheckBox,
    QTextEdit,
    QSpinBox,
    QStatusBar,
    QCompleter,
    QDateEdit,
    QDialog,
    QFrame,
    QAbstractItemView,
    QGraphicsDropShadowEffect,
    QGroupBox,
    QGridLayout,
    QHeaderView,
    QLabel,
    QFileDialog,
    QLineEdit,
    QMainWindow,
    QMessageBox,
    QMenu,
    QMenuBar,
    QPushButton,
    QScrollArea,
    QSpacerItem,
    QStackedWidget,
    QTableWidget,
    QTableWidgetItem,
    QTableView,
    QToolBar,
    QVBoxLayout,
    QWidget,
    QHBoxLayout,
    QSizePolicy,
    QFormLayout,
)


__all__ = [
    "QChart",
    "QChartView",
    "QBarSet",
    "QBarSeries",
    "QValueAxis",
    "QBarCategoryAxis",
    "QPieSeries",
    "Qt",
    "QDate",
    "QSize",
    "Signal",
    "QEvent",
    "QTimer",
    "QStringListModel",
    "QPoint",
    "QImage",
    "QAbstractTableModel",
    "QModelIndex",
    "QSortFilterProxyModel",
    "QPainter",
    "QIcon",
    "QPixmap",
    "QAction",
    "QColor",
    "QCloseEvent",
    "QFontDatabase",
    "QDoubleValidator",
    "QApplication",
    "QComboBox",
    "QCheckBox",
    "QSpinBox",
    "QCompleter",
    "QDateEdit",
    "QDialog",
    "QFrame",
    "QAbstractItemView",
    "QGraphicsDropShadowEffect",
    "QGroupBox",
    "QGridLayout",
    "QHeaderView",
    "QLabel",
    "QFileDialog",
    "QLineEdit",
    "QMainWindow",
    "QMessageBox",
    "QMenu",
    "QMenuBar",
    "QPushButton",
    "QScrollArea",
    "QSpacerItem",
    "QStackedWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTableView",
    "QTextEdit",
    "QToolBar",
    "QVBoxLayout",
    "QWidget",
    "QHBoxLayout",
    "QSizePolicy",
    "QFormLayout",
    "QFont",
    "QMouseEvent",
    "QPieSlice",
    "QStatusBar",
    "QObject",
    "QPropertyAnimation",
    "QEasingCurve",
    "QPalette",
]
